function cfg = create_configurations(basePath)
% CREATE_CONFIGURATIONS
%
% Kozponti konfiguracios struktura grid-connected PV+BESS
% onfogyasztas-novelesi vizsgalathoz.
%
% Ez a verzio mar nem off-grid PV+BESS+diesel rendszerhez keszult.
% A diesel generatorhoz es LPSP-hez kotodo metrikak kikerultek.
%
% Fobb cel:
%   - PV+BESS rendszer meretezese ipari fogyasztora
%   - onfogyasztas novelese
%   - grid import/export csokkentes vizsgalata
%   - vesztesegmetrikak megtartasa

    cfg = struct();
    % System topology
    % ---------------------------------------------------------------------
    % "dc" = DC-csatolt PV+BESS
    % "ac" = AC-csatolt PV+BESS
    cfg.system.bessCoupling = "dc";

    cfg.loadScale = 1.0;

    % ---------------------------------------------------------------------
    % Grid connection
    % ---------------------------------------------------------------------
    cfg.grid.allowExport = false;
    % ---------------------------------------------------------------------
    % Paths
    % ---------------------------------------------------------------------
    cfg.paths.base = basePath;
    cfg.paths.results = fullfile(basePath, 'results');
    cfg.paths.figures = fullfile(cfg.paths.results, 'figures');

    cfg.analysis.simYears = 4;
    
    %lifetime years and discount rate
    cfg.cost.project_lifetime_years = 15;
    cfg.cost.pv_lifetime_years = 25;
    cfg.cost.inverter_lifetime_years = 15;
    cfg.cost.discount_rate = 0.06;
    
    %Costs
    cfg.cost.eur_to_huf = 350;
    % cfg.cost.pv_huf_per_kWp = cfg.cost.eur_to_huf*500;
    cfg.cost.bess_huf_per_kWh = cfg.cost.eur_to_huf * 280;
    cfg.cost.pv_huf_per_kWp = 300000;
    %cfg.cost.bess_huf_per_kWh = 80000;
    cfg.cost.bess_power_huf_per_kW = 0;
    cfg.cost.inverter_huf_per_kW = 50000;

    cfg.cost.pv_opex_frac_per_year = 0.015;
    cfg.cost.bess_opex_frac_per_year = 0.020;
    cfg.cost.inverter_opex_frac_per_year = 0.010;

    cfg.cost.grid_import_huf_per_kWh = 100;
    cfg.cost.grid_export_huf_per_kWh = 0;

    if ~exist(cfg.paths.results, 'dir')
        mkdir(cfg.paths.results);
    end

    if ~exist(cfg.paths.figures, 'dir')
        mkdir(cfg.paths.figures);
    end

    cfg.candidates.designFields = { ...
    'P_inv_kW', ...
    'DCAC_ratio', ...
    'BESS_PV_ratio', ...
    'P_PV_kW', ...
    'PV_kW', ...
    'E_BESS_kWh', ...
    'P_BESS_kW', ...
    'bessDuration_h', ...
    'internalNetworkLossFraction'};

    % ---------------------------------------------------------------------
    % Candidate ranges
    % Egy candidate-et ezek kombinacioja hataroz meg:
    %
    %   P_PV_kW
    %   E_BESS_kWh = BESS_PV_ratio * P_PV_kW
    %   P_BESS_kW  = E_BESS_kWh / bessDuration_h
    %   P_inv_kW
    %
    % Diesel generator nincs ebben a felhasznalasban.
    % ---------------------------------------------------------------------
    cfg.candidates.PV_kW_base = 500;

    cfg.candidates.DCAC_ratio_vec = 1:0.5:3;
    

    % kWh/kWp jellegu arany:
    % pelda: 1.2 * 500 kW = 600 kWh
    cfg.candidates.BESS_PV_vec = 0:0.5:3;

    % Plusz inverter-meret ciklus.
    % Ezeket a candidate database kulon ciklusban jarja be.
    cfg.candidates.P_inv_kW_vec = [];

    % BESS teljesitmeny meretezese egyszeru duration alapon.
    % Pelda: 600 kWh / 2 h = 300 kW
    cfg.candidates.bessDuration_h = 2;

    % ---------------------------------------------------------------------
    % DC bus configuration
    % ---------------------------------------------------------------------
    % ---------------------------------------------------------------------
    % DC bus configuration - 1000 V class system
    % ---------------------------------------------------------------------
    % The DC bus is treated as a regulated stiff DC-link.
    %
    % For this case study we keep a 1000 V DC-link architecture.
    % The device voltage windows are defined separately for the inverter,
    % PV MPPT DC/DC and BESS bidirectional DC/DC.
    cfg.dcBus.controlMode = "fixed";

    cfg.dcBus.noMpptFallback_V = 1000;

    cfg.dcBus.V_ref_V = 1000;
    cfg.dcBus.V_candidate_vec_V = 900:25:1000;

    cfg.dcBus.inverterPreferred_V = 1000;

    cfg.dcBus.weightInverter = 0.50;
    cfg.dcBus.weightPvDcdc = 0.30;
    cfg.dcBus.weightBessDcdc = 0.20;

    % ---------------------------------------------------------------------
    % PV module and string configuration - 1000 V class system
    % ---------------------------------------------------------------------
    cfg.pv.modulePower_kWp = 0.715;
    cfg.pv.validateStringVoc = true;

    % Modul adatlapbol:
    cfg.pv.moduleVoc_STC_V = 49.5;              % peldaertek, datasheet alapjan cserelni
    cfg.pv.moduleVocTempCoeff_per_C = -0.0025; % relativ 1/C, pl. -0.25 %/C = -0.0025 1/C

    % Helyszin / tervezesi minimum cellahomerseklet:
    cfg.pv.minCellTemp_C = -10;
    
    % PV-direct esetben ez legyen az inverter/DC busz max.
    % MPPT DC/DC-s esetben ez inkabb cfg.mpptDcdc.VinMax_V.
    cfg.pv.maxStringVoltage_V = 1000;

    % 1000 V-os rendszerhez nem celszeru a string MPP feszultseget
    % tul kozel vinni az 1000 V-os maximumhoz.
    %
    % Tipikus nagy teljesitmenyu modulnal:
    %   V_mpp_module ~= 41...42 V
    %   20 modul sorban ~= 820...840 V string MPP
    cfg.pv.Ns = 18;

    cfg.pv.enforceIntegerStrings = true;
    cfg.pv.stringRoundingMode = "round";

        % ---------------------------------------------------------------------
    % PV MPPT DC/DC converter model - 1000 V class DC optimizer
    % ---------------------------------------------------------------------
    % Function:
    %   PV string MPP voltage -> regulated common DC bus
    %
    % Interpretation:
    %   Uin  = PV string MPP voltage
    %   Uout = common DC-link voltage
    %
    % The efficiency values are high because this represents a PV-side
    % DC optimizer / MPPT DC/DC, not the BESS battery converter.
    cfg.mpptDcdc.enabled = false;
    cfg.mpptDcdc.loadFractionCurve = ...
        [0.00 0.02 0.05 0.10 0.20 0.50 0.75 1.00];

    cfg.mpptDcdc.etaLoadCurve = ...
        [0.00 0.985 0.992 0.994 0.995 0.9955 0.995 0.994];

    % Voltage-ratio correction factor, not a second absolute efficiency.
    % ratio = Uin / Uout = V_pv_mpp / V_dc_link
    cfg.mpptDcdc.voltageRatioCurve = ...
        [0.30 0.50 0.65 0.80 0.90 1.00 1.10 1.25];

    cfg.mpptDcdc.etaVoltageCurve = ...
        [0.985 0.992 0.996 0.999 1.000 1.000 0.998 0.995];

    cfg.mpptDcdc.etaMin = 0.00;
    cfg.mpptDcdc.etaMax = 0.9955;

    % 1000 V-os PV DC optimizer / MPPT DC/DC feszultsegtartomany.
    cfg.mpptDcdc.VinMin_V = 300;
    cfg.mpptDcdc.VinMax_V = 1000;

    cfg.mpptDcdc.VoutMin_V = 500;
    cfg.mpptDcdc.VoutMax_V = 1000;

    % Ezeket aggregalt MPPT-csoportkent kezeljuk, ezert nem egyetlen
    % fizikai optimizer 50 A-es aramkorlatat hasznaljuk itt.
    cfg.mpptDcdc.IinMax_A = inf;
    cfg.mpptDcdc.IoutMax_A = inf;

    cfg.mpptDcdc.ratioMin = min(cfg.mpptDcdc.voltageRatioCurve);
    cfg.mpptDcdc.ratioMax = max(cfg.mpptDcdc.voltageRatioCurve);

    % ---------------------------------------------------------------------
    % BESS bidirectional DC/DC converter model - 500...1500 V ports
    % ---------------------------------------------------------------------
    % Function:
    %   BESS rack/string <-> common DC bus
    %
    % Interpretation:
    %   high side = common DC bus side
    %   low side  = BESS rack / battery side
    %
    % The converter voltage range is intentionally wider than the selected
    % 1000 V operating point, because such units can be suitable for both
    % 1000 V and 1500 V class DC systems.
    cfg.bessDcdc.loadFractionCurve = ...
        [0.00 0.01 0.02 0.05 0.10 0.20 0.50 0.75 1.00];

    % Load-dependent absolute efficiency.
    % The curve is built from a realistic average/peak behaviour:
    %   - weak operation at very low part load,
    %   - good operation above 10...20% loading,
    %   - peak around mid/high load.
    cfg.bessDcdc.etaLoadCurve = ...
        [0.00 0.80 0.90 0.94 0.960 0.972 0.982 0.985 0.980];

    % Voltage-ratio correction factor.
    % ratio = Uin / Uout
    % discharge: Uin = V_bess, Uout = V_dc_link
    % charge:    Uin = V_dc_link, Uout = V_bess
    cfg.bessDcdc.voltageRatioCurve = ...
        [0.35 0.50 0.65 0.80 0.90 1.00 1.10 1.25 1.50 2.00 2.50 3.00];

    cfg.bessDcdc.etaVoltageCurve = ...
        [0.955 0.970 0.982 0.992 0.997 1.000 0.997 0.993 0.985 0.972 0.960 0.950];

    cfg.bessDcdc.etaMin = 0.00;
    cfg.bessDcdc.etaMax = 0.985;

    % Converter voltage windows.
    % High side: common DC bus side.
    cfg.bessDcdc.VhighNom_V = 1000;
    cfg.bessDcdc.VhighMin_V = 500;
    cfg.bessDcdc.VhighMax_V = 1500;

    % Low side: BESS rack / pack side.
    cfg.bessDcdc.VlowNom_V = 864;
    cfg.bessDcdc.VlowMin_V = 500;
    cfg.bessDcdc.VlowMax_V = 1500;

    cfg.bessDcdc.IhighMax_A = inf;
    cfg.bessDcdc.IlowMax_A = inf;

    cfg.bessDcdc.ratioMin = min(cfg.bessDcdc.voltageRatioCurve);
    cfg.bessDcdc.ratioMax = max(cfg.bessDcdc.voltageRatioCurve);

    cfg.bessDcdc.etaChargeFactor = 0.997;
    cfg.bessDcdc.etaDischargeFactor = 1.000;
    % ---------------------------------------------------------------------
    % Inverter / PCS efficiency model - 1000 V DC input class
    % ---------------------------------------------------------------------
    cfg.inverter.efficiencyModel = "curve";

    % 1000 V-os DC oldali inverter / PCS tartomany.
    cfg.inverter.VdcNom_V = 1000;
    cfg.inverter.VdcMin_V = 470;
    cfg.inverter.VdcMax_V = 1000;

    % Power-dependent efficiency curve.
    % loadFraction = P_ac_out / P_inv_nom
    cfg.inverter.loadFractionCurve = ...
        [0.00 0.02 0.05 0.10 0.20 0.50 0.75 1.00];

    cfg.inverter.etaCurve = ...
        [0.00 0.90 0.945 0.965 0.975 0.985 0.984 0.980];

    cfg.inverter.etaMin = 0.80;
    cfg.inverter.etaMax = 0.985;

    % These are only used if efficiencyModel = "parabolic".
    cfg.inverter.loadOpt = 0.55;
    cfg.inverter.curvature = 0.08;
    cfg.inverter.minActiveLoadFraction = 1e-6;

    % ---------------------------------------------------------------------
    % Diagnostics
    % ---------------------------------------------------------------------
    cfg.diagnostics.enabled = true;
    cfg.diagnostics.testMode = false;
    cfg.diagnostics.candidateIndex = 1;
    cfg.diagnostics.coupling = "dc";

    cfg.diagnostics.outputFolder = fullfile(cfg.paths.results, 'diagnostics');
    
    % Minden napra egy egyszerusitett napi abra.
    cfg.diagnostics.plotEveryDay = true;

    % A regi heti es osszefoglalo abrak nem kellenek.
    cfg.diagnostics.makeWeekPlots = false;
    cfg.diagnostics.makeDailySummaryPlot = false;

    cfg.diagnostics.saveFullTimeSeries = true;
    cfg.diagnostics.saveFigFiles = true;

    cfg.diagnostics.plotFullHorizonVoltages = true;

    cfg.diagnostics.plotEveryDay = false;
    cfg.diagnostics.plotDayIndices = [];

    cfg.diagnostics.minBessChargeEnergy_kWh = 100.0;
    cfg.diagnostics.maxDiagnosticDaysToPlot = 6;

    cfg.diagnostics.includeLowPvDays = true;
    cfg.diagnostics.nLowPvDaysToPlot = 4;
    cfg.diagnostics.lowPvMinEnergy_kWh = 2.0;

    cfg.diagnostics.showFigures = false;
    cfg.diagnostics.closeFiguresAfterSave = true;

    % ---------------------------------------------------------------------
    % BESS rack / pack configuration - 1000 V class
    % ---------------------------------------------------------------------
    cfg.bess.cellCapacity_Ah = 280;
    cfg.bess.cellNominalVoltage_V = 3.2;

    % 1000 V-os rendszerhez illesztett LFP rack/string.
    %
    % Nominal:
    %   270 * 3.2 V  = 864 V
    %
    % Upper voltage estimate:
    %   270 * 3.65 V = 985.5 V
    %
    % This keeps the BESS pack in a realistic 1000 V class range.
    cfg.bess.Ns = 270;
    cfg.bess.V_nominal_pack = cfg.bess.Ns * cfg.bess.cellNominalVoltage_V;

    cfg.bess.SoC_initial = 0.50;

    % ---------------------------------------------------------------------
    % PV
    % ---------------------------------------------------------------------
    cfg.pv.tiltX = 35;
    cfg.pv.tiltZ = 180;
    cfg.pv.referencePdc_kWp = 1.0;
    cfg.pv.modulePower_kWp = 0.5;
    % ---------------------------------------------------------------------
    % PV module and string configuration
    % ---------------------------------------------------------------------
    cfg.pv.modulePower_kWp = 0.715;
    cfg.pv.Ns = 24;

    % If false:
    %   the parameter sweep keeps the exact requested PV size.
    %
    % If true:
    %   PV sizes are rounded to integer parallel string numbers.
    cfg.pv.enforceIntegerStrings = true;

    % Options:
    %   "round", "ceil", "floor"
    cfg.pv.stringRoundingMode = "round";

    % ---------------------------------------------------------------------
    % BESS
    % ---------------------------------------------------------------------
    bess_pars = base_battery_pars_nonideal_(100, 50);

    cfg.bess.SoC_min = bess_pars.SoC_min;
    cfg.bess.SoC_max = bess_pars.SoC_max;
    cfg.bess.SoC_initial = bess_pars.SoC_init;
    cfg.bess.eta_ch = bess_pars.eta_c;
    cfg.bess.eta_dis = bess_pars.eta_d;

    % ---------------------------------------------------------------------
    % Inverter
    % Teljesitmenyfuggo hatasfokgorbe.
    % loadFraction = P_ac_out / P_inv_nom
    % ---------------------------------------------------------------------
    cfg.inverter.loadFractionCurve = [0.00 0.05 0.10 0.20 0.50 0.75 1.00];
    cfg.inverter.etaCurve          = [0.00 0.88 0.92 0.95 0.97 0.965 0.955];
    cfg.inverter.etaMin = 0.80;
    cfg.inverter.etaMax = 0.98;

    % A szimulaciohoz hasznalt inverter candidate-ek:
    %   P80, P90, P95, P100 fogyasztasi teljesitmeny percentilisekbol jonnek.
    % ---------------------------------------------------------------------
    cfg.analysis.makePlots = true;

    % Elemzesi PV meret csak az elozetes PV-load illeszkedes abrahoz kell.
    % Az inverter meretezest ez NEM befolyasolja.
    cfg.analysis.PV_kW_forAnalysis = 1000;

    cfg.analysis.inverterSizing.percentiles = [80 90 95 100];

    % Ezek csak a reszletes percentilis tablazathoz kellenek.
    cfg.analysis.inverterSizing.reportPercentiles = [50 75 80 90 95 98 99 100];

    % Inverter meretek felkerekitesi lepese.
    cfg.analysis.inverterSizing.roundStep_kW = 50;

    % Hisztogram osztaskoz.
    cfg.analysis.inverterSizing.histBinWidth_kW = 25;

    % Mivel a 100. percentilis mar benne van, nem kell kulon maximumot hozzaadni.
    cfg.analysis.inverterSizing.includeMaximum = false;

    % Maximum 4 inverter meretet szeretnenk.
    cfg.analysis.inverterSizing.maxCandidateCount = 4;

    % Mar nem fix invertermeretet hasznalunk, hanem candidate ciklust.
    % Ez csak fallback, ha valahol regi kod meg ezt varja.
    cfg.inverter.P_inv_kW = 0;

    % ---------------------------------------------------------------------
    % Internal network / transformer losses
    % Konstans belso halozati es transzformator veszteseg.
    % ---------------------------------------------------------------------
    cfg.internalNetwork.lossFraction = 0.025;

    % ---------------------------------------------------------------------
    % Costs
    % Ezek tovabbra is helytarto ertekek, kesobb pontosithatok.
    % ---------------------------------------------------------------------
    % cfg.cost.pv_huf_per_kWp = 250000;
    % cfg.cost.bess_huf_per_kWh = 120000;
    % cfg.cost.bess_power_huf_per_kW = 0;
    % cfg.cost.inverter_huf_per_kW = 50000;

    % Grid-connected self-consumption gazdasagi parameterek.
    cfg.cost.grid_import_huf_per_kWh = 75;
    cfg.cost.grid_export_huf_per_kWh = 0;

    % ---------------------------------------------------------------------
    % Simulation / storage
    % ---------------------------------------------------------------------
    cfg.sim.saveAfterEachCandidate = true;
    cfg.sim.verbose = true;

    % Ha true, akkor a metrikafrissites hibat dob, ha egy dayVectors source
    % mezo hianyzik.
    cfg.sim.strictMetricSources = true;

    % Evaluation
    % ---------------------------------------------------------------------
    cfg.evaluation = struct();

    % Ezt a MAT fajlt tolti be az evaluation()
    if cfg.system.bessCoupling == "dc"
        cfg.evaluation.resultFileName = "results_dccoupled.mat";
    else
        cfg.evaluation.resultFileName = "results_accoupled.mat";
    end

    % Szimulalt idoszak hossza evben
    cfg.evaluation.simYears = 3;

    % Legjobb rendszer kivalasztasi modja:
    % "minLCSE", "minLCOE", "maxNPV", "minPayback", "minStaticPayback", "maxIRR"
    cfg.evaluation.selectionMode = "minLCSE";

    % Szurok a legjobb candidate valasztashoz
    cfg.evaluation.minGridImportReduction_pct = 0;
    cfg.evaluation.requirePositiveNPV = false;
    cfg.evaluation.requireBESS = false;

    % Ha false: csak LCSE, LCOE, NPV kap 3D scatter + heatmap abrat
    % Ha true: minden implementalt mutato kap 3D scatter + heatmap abrat
    cfg.evaluation.plotAllMetricMaps = false;

    
    % ---------------------------------------------------------------------
    % Diagnostics
    % ---------------------------------------------------------------------
    cfg.diagnostics.enabled = true;
    cfg.diagnostics.testMode = false;

    % CandidateTable sorszama.
    cfg.diagnostics.candidateIndex = 10;

    % A reszletes DC busz / MPPT / buck-boost diagnosztikahoz DC kell.
    cfg.diagnostics.coupling = "dc";

    cfg.diagnostics.outputFolder = fullfile(cfg.paths.results, 'diagnostics');

    cfg.diagnostics.saveFullTimeSeries = true;
    cfg.diagnostics.makeDcCoupledSummaryPlots = true;
    cfg.diagnostics.saveFigFiles = true;

    % Ha ures, automatikus napvalasztas.
    cfg.diagnostics.plotDayIndices = [];

    % Kezi napvalasztas pelda:
    % cfg.diagnostics.plotDayIndices = [1 100 200];

    cfg.diagnostics.plotWeekStartDays = [];
    cfg.diagnostics.socTolerance = 0.02;
    cfg.diagnostics.expectedCycleWarningRatio = 0.30;
    % ---------------------------------------------------------------------
    % OUTPUT METRICS - SCALAR
    % ---------------------------------------------------------------------
    % A napi szimulacios fuggvenynek ezeket a dayVectors mezoket kell
    % eloallitani.
    %
    % Grid-connected self-consumption dayVectors ajanlott mezok:
    %
    %   P_load_kW
    %   P_pv_available_kW
    %   P_pv_to_load_kW
    %   P_pv_to_bess_kW
    %   P_bess_to_load_kW
    %   P_grid_import_kW
    %   P_grid_export_kW
    %   P_curtailment_kW
    %   P_inv_loss_kW
    %   P_internal_network_loss_kW
    %
    % Vesztesegmezok:
    %   P_bess_cell_loss_kW
    %   P_bess_soc_full_loss_kW
    %   P_bess_soc_empty_loss_kW
    %   P_bess_total_internal_loss_kW
    %   P_dcdc_conversion_loss_kW
    %   P_dcdc_power_clipped_kW
    %   P_inv_conversion_loss_kW
    %   P_inv_power_clipped_kW
    %   P_inv_pv_conversion_loss_kW
    %   P_inv_bess_conversion_loss_kW
    %   P_inv_pv_clipped_kW
    %   P_inv_bess_clipped_kW
    % ---------------------------------------------------------------------

    cfg.output.scalarMetrics = struct( ...
    'name', { ...
        'loadEnergy_kWh', ...
        'pvEnergyAvailable_kWh', ...
        'pvToLoad_kWh', ...
        'pvToBess_kWh', ...
        'bessToLoad_kWh', ...
        'gridImport_kWh', ...
        'gridExport_kWh', ...
        'curtailment_kWh', ...
        'inverterLoss_kWh', ...
        'internalNetworkLoss_kWh', ...
        'maxLoadPeak_kW', ...
        'maxPVPeak_kW', ...
        'maxGridImportPeak_kW', ...
        'maxGridExportPeak_kW', ...
        'maxBessChargePeak_kW', ...
        'maxBessDischargePeak_kW' ...
    }, ...
    'source', { ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_pv_to_load_kW', ...
        'P_pv_to_bess_kW', ...
        'P_bess_to_load_kW', ...
        'P_grid_import_kW', ...
        'P_grid_export_kW', ...
        'P_curtailment_kW', ...
        'P_inv_loss_kW', ...
        'P_internal_network_loss_kW', ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_grid_import_kW', ...
        'P_grid_export_kW', ...
        'P_pv_to_bess_kW', ...
        'P_bess_to_load_kW' ...
    }, ...
    'mode', { ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'max', ...
        'max', ...
        'max', ...
        'max', ...
        'max', ...
        'max' ...
    });

    extraScalarLossMetrics = struct( ...
    'name', { ...
        'bessCellLoss_kWh', ...
        'bessSocFullLoss_kWh', ...
        'bessSocEmptyLoss_kWh', ...
        'bessTotalInternalLoss_kWh', ...
        'dcdcConversionLoss_kWh', ...
        'dcdcPowerClipped_kWh', ...
        'inverterConversionLoss_kWh', ...
        'inverterPowerClipped_kWh', ...
        'inverterPvConversionLoss_kWh', ...
        'inverterBessConversionLoss_kWh', ...
        'inverterPvClipped_kWh', ...
        'inverterBessClipped_kWh' ...
    }, ...
    'source', { ...
        'P_bess_cell_loss_kW', ...
        'P_bess_soc_full_loss_kW', ...
        'P_bess_soc_empty_loss_kW', ...
        'P_bess_total_internal_loss_kW', ...
        'P_dcdc_conversion_loss_kW', ...
        'P_dcdc_power_clipped_kW', ...
        'P_inv_conversion_loss_kW', ...
        'P_inv_power_clipped_kW', ...
        'P_inv_pv_conversion_loss_kW', ...
        'P_inv_bess_conversion_loss_kW', ...
        'P_inv_pv_clipped_kW', ...
        'P_inv_bess_clipped_kW' ...
    }, ...
    'mode', { ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum' ...
    });

    cfg.output.scalarMetrics = [cfg.output.scalarMetrics, extraScalarLossMetrics];

    % ---------------------------------------------------------------------
    % OUTPUT METRICS - PROFILE
    % ---------------------------------------------------------------------
    cfg.output.profileMetrics = struct( ...
    'name', { ...
        'meanLoad_kW', ...
        'peakLoad_kW', ...
        'meanPvAvailable_kW', ...
        'peakPvAvailable_kW', ...
        'meanPvToLoad_kW', ...
        'peakPvToLoad_kW', ...
        'meanPvToBess_kW', ...
        'peakPvToBess_kW', ...
        'meanBessToLoad_kW', ...
        'peakBessToLoad_kW', ...
        'meanGridImport_kW', ...
        'peakGridImport_kW', ...
        'meanGridExport_kW', ...
        'peakGridExport_kW', ...
        'meanCurtailmentPower_kW', ...
        'peakCurtailmentPower_kW', ...
        'meanSoC', ...
        'minSoC', ...
        'maxSoC', ...
        'meanInverterLoss_kW', ...
        'peakInverterLoss_kW', ...
        'meanInternalNetworkLoss_kW', ...
        'peakInternalNetworkLoss_kW' ...
    }, ...
    'source', { ...
        'P_load_kW', ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_pv_available_kW', ...
        'P_pv_to_load_kW', ...
        'P_pv_to_load_kW', ...
        'P_pv_to_bess_kW', ...
        'P_pv_to_bess_kW', ...
        'P_bess_to_load_kW', ...
        'P_bess_to_load_kW', ...
        'P_grid_import_kW', ...
        'P_grid_import_kW', ...
        'P_grid_export_kW', ...
        'P_grid_export_kW', ...
        'P_curtailment_kW', ...
        'P_curtailment_kW', ...
        'SoC', ...
        'SoC', ...
        'SoC', ...
        'P_inv_loss_kW', ...
        'P_inv_loss_kW', ...
        'P_internal_network_loss_kW', ...
        'P_internal_network_loss_kW' ...
    }, ...
    'mode', { ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'minProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile' ...
    });

    extraProfileLossMetrics = struct( ...
    'name', { ...
        'meanBessCellLoss_kW', ...
        'peakBessCellLoss_kW', ...
        'meanBessSocFullLoss_kW', ...
        'peakBessSocFullLoss_kW', ...
        'meanBessSocEmptyLoss_kW', ...
        'peakBessSocEmptyLoss_kW', ...
        'meanDcdcConversionLoss_kW', ...
        'peakDcdcConversionLoss_kW', ...
        'meanDcdcPowerClipped_kW', ...
        'peakDcdcPowerClipped_kW', ...
        'meanInverterConversionLoss_kW', ...
        'peakInverterConversionLoss_kW', ...
        'meanInverterPowerClipped_kW', ...
        'peakInverterPowerClipped_kW', ...
        'meanInverterPvConversionLoss_kW', ...
        'peakInverterPvConversionLoss_kW', ...
        'meanInverterBessConversionLoss_kW', ...
        'peakInverterBessConversionLoss_kW', ...
        'meanInverterPvClipped_kW', ...
        'peakInverterPvClipped_kW', ...
        'meanInverterBessClipped_kW', ...
        'peakInverterBessClipped_kW' ...
    }, ...
    'source', { ...
        'P_bess_cell_loss_kW', ...
        'P_bess_cell_loss_kW', ...
        'P_bess_soc_full_loss_kW', ...
        'P_bess_soc_full_loss_kW', ...
        'P_bess_soc_empty_loss_kW', ...
        'P_bess_soc_empty_loss_kW', ...
        'P_dcdc_conversion_loss_kW', ...
        'P_dcdc_conversion_loss_kW', ...
        'P_dcdc_power_clipped_kW', ...
        'P_dcdc_power_clipped_kW', ...
        'P_inv_conversion_loss_kW', ...
        'P_inv_conversion_loss_kW', ...
        'P_inv_power_clipped_kW', ...
        'P_inv_power_clipped_kW', ...
        'P_inv_pv_conversion_loss_kW', ...
        'P_inv_pv_conversion_loss_kW', ...
        'P_inv_bess_conversion_loss_kW', ...
        'P_inv_bess_conversion_loss_kW', ...
        'P_inv_pv_clipped_kW', ...
        'P_inv_pv_clipped_kW', ...
        'P_inv_bess_clipped_kW', ...
        'P_inv_bess_clipped_kW' ...
    }, ...
    'mode', { ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile' ...
    });

    cfg.output.profileMetrics = [cfg.output.profileMetrics, extraProfileLossMetrics];
end